POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Voyage to the Ice Moons: Exploring Europa and Enceladus",
  "author": "Dr. Lyra Mendoza",
  "url": "https://astrofrontiers.org/blog/ice-moon-voyage",
  "likes": 237,
  "userId": "684a15318a12c7b62ac07ca8"
}
