POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFzdHJvX2V4cGxvcmVyIiwiaWQiOiI2ODRiNGQwZWJhNmNjYWU0ODI3ZTRhNTEiLCJpYXQiOjE3NDk4MzA0NjcsImV4cCI6MTc0OTgzNDA2N30.WgovqCo_OsHObVQsSMIlibQIwL8ARzlxUypacZYup4A

{
  "title": "Power and Perception: How Media Shapes Modern Politics",
  "author": "Dana L. Everett",
  "url": "https://mindsonmath.org/blog/media-and-politics",
  "likes": 142
}