POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFzdHJvX2V4cGxvcmVyIiwiaWQiOiI2ODRiNGQwZWJhNmNjYWU0ODI3ZTRhNTEiLCJpYXQiOjE3NDk3NjU4NTAsImV4cCI6MTc0OTc2OTQ1MH0.nqv5zHZ2q68NPjDERt35j5rzhZrN5myeRxwN5U4rxeQ

{
  "title": "The Hidden Geometry of Nature: Why Trees, Shells, and Storms Follow Math",
  "author": "Elliot R. Thorne",
  "url": "https://mindsonmath.org/blog/hidden-geometry",
  "likes": 89
}
